// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9mJKlEP22K1i-AU9ID143I_k0osXPccg',
    appId: '1:388213060628:web:5df3d2ad0bc47b91f0e301',
    messagingSenderId: '388213060628',
    projectId: 'artie-sans',
    authDomain: 'artie-sans.firebaseapp.com',
    storageBucket: 'artie-sans.firebasestorage.app',
    measurementId: 'G-F6BK0PFKJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Y99wVUB-EVnIBiNEIatXFLGEidPhWLI',
    appId: '1:388213060628:android:c3ca00ac0a368398f0e301',
    messagingSenderId: '388213060628',
    projectId: 'artie-sans',
    storageBucket: 'artie-sans.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUPPsQCN9a9YiHJlhXJNTbhjjrUSvsdWQ',
    appId: '1:388213060628:ios:7fb022603aafea30f0e301',
    messagingSenderId: '388213060628',
    projectId: 'artie-sans',
    storageBucket: 'artie-sans.firebasestorage.app',
    androidClientId: '388213060628-37k5155bocoipa4iv2k10kka8qfaumvo.apps.googleusercontent.com',
    iosClientId: '388213060628-vm3l9q8mba2pd4cgu7nt2idcn0fv3p5v.apps.googleusercontent.com',
    iosBundleId: 'com.example.arti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUPPsQCN9a9YiHJlhXJNTbhjjrUSvsdWQ',
    appId: '1:388213060628:ios:7fb022603aafea30f0e301',
    messagingSenderId: '388213060628',
    projectId: 'artie-sans',
    storageBucket: 'artie-sans.firebasestorage.app',
    androidClientId: '388213060628-37k5155bocoipa4iv2k10kka8qfaumvo.apps.googleusercontent.com',
    iosClientId: '388213060628-vm3l9q8mba2pd4cgu7nt2idcn0fv3p5v.apps.googleusercontent.com',
    iosBundleId: 'com.example.arti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9mJKlEP22K1i-AU9ID143I_k0osXPccg',
    appId: '1:388213060628:web:e700181fec5d9375f0e301',
    messagingSenderId: '388213060628',
    projectId: 'artie-sans',
    authDomain: 'artie-sans.firebaseapp.com',
    storageBucket: 'artie-sans.firebasestorage.app',
    measurementId: 'G-9ZFYV09VBF',
  );

}
