// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTVZNN8CWaev6S0N3QhXHEa_4I15RwkoE',
    appId: '1:407125431738:web:b6b197a6c0dfb83e74f983',
    messagingSenderId: '407125431738',
    projectId: 'garti-sans',
    authDomain: 'garti-sans.firebaseapp.com',
    storageBucket: 'garti-sans.firebasestorage.app',
    measurementId: 'G-09HMQL8529',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBK1IFyhN7D2Z0AkOwduDONaU1pAqyp4A',
    appId: '1:407125431738:android:6ea65fc0b3f3f7d574f983',
    messagingSenderId: '407125431738',
    projectId: 'garti-sans',
    storageBucket: 'garti-sans.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtFTafqLYFdrwozGLIexJOjAwWvC7KRFI',
    appId: '1:407125431738:ios:f2d1fe6bc81b3c2474f983',
    messagingSenderId: '407125431738',
    projectId: 'garti-sans',
    storageBucket: 'garti-sans.firebasestorage.app',
    androidClientId: '407125431738-1ra99k19cn38aj7j30e2kvfr6anae43j.apps.googleusercontent.com',
    iosClientId: '407125431738-s9qb7uees3gkusbl440tgs85mh1o6rnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.arti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtFTafqLYFdrwozGLIexJOjAwWvC7KRFI',
    appId: '1:407125431738:ios:f2d1fe6bc81b3c2474f983',
    messagingSenderId: '407125431738',
    projectId: 'garti-sans',
    storageBucket: 'garti-sans.firebasestorage.app',
    androidClientId: '407125431738-1ra99k19cn38aj7j30e2kvfr6anae43j.apps.googleusercontent.com',
    iosClientId: '407125431738-s9qb7uees3gkusbl440tgs85mh1o6rnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.arti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTVZNN8CWaev6S0N3QhXHEa_4I15RwkoE',
    appId: '1:407125431738:web:19972b0fd05fd04e74f983',
    messagingSenderId: '407125431738',
    projectId: 'garti-sans',
    authDomain: 'garti-sans.firebaseapp.com',
    storageBucket: 'garti-sans.firebasestorage.app',
    measurementId: 'G-MPZDLV3L7C',
  );

}